return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "go",
      "gosum",
      "gomod",
      "git_config",
      "graphql",
      "hcl",
      "html",
      "ini",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "make",
      "markdown",
      "mermaid",
      "python",
      "scss",
      "sql",
      "toml",
      "tsx",
      "vim",
      "xml",
      "yaml",
    },
    auto_install = "true",
    highlight = {
      enable = true,
      use_languagetree = true,
    },
  },
}
